import { StyleSheet, Text, View } from 'react-native';
import { MoonStar, Sparkles, TrendingUp, Zap } from 'lucide-react-native';
import { Screen } from '@/components/Screen'; import { Card, Eyebrow } from '@/components/ui'; import { colors } from '@/lib/theme';
const week=[72,81,68,88,76,84,90];
export default function Insights(){return <Screen><View style={s.header}><Eyebrow>GENTLE PATTERNS</Eyebrow><Text style={s.title}>Your insights</Text><Text style={s.sub}>Small clues about what helps you feel like you.</Text></View>
 <Card><View style={s.chartHead}><View><Text style={s.cardTitle}>This week’s glow</Text><Text style={s.delta}>↗ 8% from last week</Text></View><View style={s.pill}><Text style={s.pillText}>WEEK</Text></View></View><View style={s.chart}>{week.map((n,i)=><View key={i} style={s.barCol}><View style={s.barTrack}><View style={[s.bar,{height:`${n}%`}]} /></View><Text style={s.day}>{['S','M','T','W','T','F','S'][i]}</Text></View>)}</View></Card>
 <Text style={s.section}>What we’re noticing</Text><Card style={s.feature}><View style={s.icon}><Sparkles size={20} color={colors.gold}/></View><View style={{flex:1}}><Eyebrow>A LOVELY CONNECTION</Eyebrow><Text style={s.featureTitle}>Sleep is your secret ingredient</Text><Text style={s.featureText}>On nights you sleep well, your happiness is about 14% higher the next day.</Text></View></Card>
 <View style={s.row}><Metric icon={<Zap size={19} color="#D98967"/>} color="#FFF0E9" value="78%" label="ENERGY" note="Steady this week"/><Metric icon={<MoonStar size={19} color="#887BAC"/>} color="#F0EDF8" value="82%" label="SLEEP" note="Your best yet"/></View>
 <Card style={s.tip}><TrendingUp size={21} color={colors.sage}/><View style={{flex:1}}><Text style={s.tipTitle}>A gentle nudge</Text><Text style={s.tipText}>Your afternoons look brighter on days you step outside. A ten-minute walk might be just enough.</Text></View></Card>
 </Screen>}
function Metric({icon,color,value,label,note}:any){return <Card style={s.metric}><View style={[s.metricIcon,{backgroundColor:color}]}>{icon}</View><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text><Text style={s.metricNote}>{note}</Text></Card>}
const s=StyleSheet.create({header:{paddingTop:18,paddingBottom:22},title:{fontFamily:'BodoniModa_700Bold',fontSize:34,color:colors.ink,marginTop:3},sub:{fontFamily:'DMSans_400Regular',fontSize:13,color:colors.muted,marginTop:4},chartHead:{flexDirection:'row',justifyContent:'space-between'},cardTitle:{fontFamily:'DMSans_700Bold',fontSize:15,color:colors.ink},delta:{fontFamily:'DMSans_600SemiBold',fontSize:10,color:colors.sage,marginTop:4},pill:{backgroundColor:'#FBEAED',borderRadius:13,paddingHorizontal:11,paddingVertical:7},pillText:{fontFamily:'DMSans_700Bold',fontSize:8,color:colors.rose,letterSpacing:1},chart:{height:170,flexDirection:'row',gap:9,alignItems:'flex-end',marginTop:22},barCol:{flex:1,height:'100%',alignItems:'center'},barTrack:{flex:1,width:'68%',borderRadius:8,backgroundColor:'#F8EDEF',justifyContent:'flex-end',overflow:'hidden'},bar:{width:'100%',borderRadius:8,backgroundColor:colors.blush},day:{fontFamily:'DMSans_600SemiBold',fontSize:9,color:colors.muted,marginTop:8},section:{fontFamily:'BodoniModa_700Bold',fontSize:23,color:colors.ink,marginTop:25,marginBottom:12},feature:{flexDirection:'row',gap:14,alignItems:'flex-start'},icon:{width:44,height:44,borderRadius:15,backgroundColor:'#FFF5DF',alignItems:'center',justifyContent:'center'},featureTitle:{fontFamily:'DMSans_700Bold',fontSize:14,color:colors.ink,marginTop:5},featureText:{fontFamily:'DMSans_400Regular',fontSize:12,lineHeight:18,color:colors.muted,marginTop:5},row:{flexDirection:'row',gap:12,marginTop:12},metric:{flex:1},metricIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center'},metricValue:{fontFamily:'BodoniModa_700Bold',fontSize:34,color:colors.ink,marginTop:9},metricLabel:{fontFamily:'DMSans_700Bold',fontSize:9,letterSpacing:1.2,color:colors.gold},metricNote:{fontFamily:'DMSans_400Regular',fontSize:10,color:colors.muted,marginTop:4},tip:{marginTop:12,flexDirection:'row',gap:13,backgroundColor:'#F1F7F2'},tipTitle:{fontFamily:'DMSans_700Bold',fontSize:13,color:colors.ink},tipText:{fontFamily:'DMSans_400Regular',fontSize:11,lineHeight:17,color:colors.muted,marginTop:3}});
