import { StyleSheet, Text, View } from 'react-native';
import { ChevronLeft, ChevronRight, Flame } from 'lucide-react-native';
import { Screen } from '@/components/Screen';
import { Card, Eyebrow } from '@/components/ui';
import { colors } from '@/lib/theme';
import { useHappinessStore } from '@/lib/store';

const days = Array.from({length:35},(_,i)=> i < 2 ? null : i-1);
const scores: Record<number,number> = {29:72,30:81,1:68,2:88,3:76,4:84,5:90};
export default function Journey(){ const streak=useHappinessStore(s=>s.streak); return <Screen>
  <View style={s.header}><View><Eyebrow>YOUR JOURNEY</Eyebrow><Text style={s.title}>A month in bloom</Text></View><View style={s.streak}><Flame size={16} color="#E8895F"/><Text style={s.streakText}>{streak} day streak</Text></View></View>
  <Card><View style={s.month}><ChevronLeft size={19} color={colors.muted}/><Text style={s.monthText}>July 2026</Text><ChevronRight size={19} color={colors.muted}/></View><View style={s.week}>{['S','M','T','W','T','F','S'].map((x,i)=><Text key={i} style={s.weekText}>{x}</Text>)}</View><View style={s.grid}>{days.map((d,i)=><View key={i} style={s.cell}>{d ? <View style={[s.day, scores[d] ? {backgroundColor:scores[d]>80?'#E1F0E5':scores[d]>70?'#FCEBC8':'#F8DEE3'} : undefined]}><Text style={[s.dayText,scores[d] ? {color:colors.ink} : undefined]}>{d}</Text>{scores[d] ? <View style={[s.dayDot,{backgroundColor:scores[d]>80?colors.sage:scores[d]>70?colors.gold:colors.rose}]}/> : null}</View> : null}</View>)}</View></Card>
  <Text style={s.section}>July, so far</Text><View style={s.stats}><Card style={s.stat}><Text style={s.statNum}>80%</Text><Text style={s.statLabel}>AVG. HAPPINESS</Text></Card><Card style={s.stat}><Text style={s.statNum}>7</Text><Text style={s.statLabel}>DAYS CHECKED IN</Text></Card></View>
  <Card style={s.memory}><Text style={s.memoryEmoji}>✨</Text><View style={{flex:1}}><Eyebrow>BRIGHTEST MOMENT</Eyebrow><Text style={s.memoryTitle}>Thursday felt radiant</Text><Text style={s.memoryText}>“Lunch in the sun and a really good coffee.”</Text></View></Card>
  <Card style={s.note}><Text style={s.noteText}>Your month is not a scorecard. It’s a collection of moments—and every color belongs here.</Text></Card>
 </Screen> }
const s=StyleSheet.create({header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingTop:18,paddingBottom:22},title:{fontFamily:'BodoniModa_700Bold',fontSize:30,color:colors.ink,marginTop:3},streak:{flexDirection:'row',gap:6,backgroundColor:'#FFF0E7',padding:9,borderRadius:15},streakText:{fontFamily:'DMSans_700Bold',fontSize:11,color:'#9E5D40'},month:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:20},monthText:{fontFamily:'DMSans_700Bold',fontSize:15,color:colors.ink},week:{flexDirection:'row'},weekText:{width:'14.28%',textAlign:'center',fontFamily:'DMSans_700Bold',fontSize:9,color:'#AE9DA2'},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:8},cell:{width:'14.28%',height:48,alignItems:'center',justifyContent:'center'},day:{width:39,height:39,borderRadius:15,alignItems:'center',justifyContent:'center'},dayText:{fontFamily:'DMSans_600SemiBold',fontSize:12,color:'#BDAEB2'},dayDot:{position:'absolute',bottom:4,width:4,height:4,borderRadius:2},section:{fontFamily:'BodoniModa_700Bold',fontSize:23,color:colors.ink,marginTop:25,marginBottom:12},stats:{flexDirection:'row',gap:12},stat:{flex:1,alignItems:'center'},statNum:{fontFamily:'BodoniModa_700Bold',fontSize:36,color:colors.rose},statLabel:{fontFamily:'DMSans_700Bold',fontSize:8,letterSpacing:1,color:colors.gold},memory:{marginTop:12,flexDirection:'row',alignItems:'center',gap:14},memoryEmoji:{fontSize:27},memoryTitle:{fontFamily:'DMSans_700Bold',fontSize:14,color:colors.ink,marginTop:4},memoryText:{fontFamily:'DMSans_400Regular',fontSize:11,color:colors.muted,marginTop:3},note:{marginTop:12,backgroundColor:'#F7EFF8'},noteText:{fontFamily:'BodoniModa_600SemiBold',fontSize:17,lineHeight:23,color:'#75627E',textAlign:'center'}});
