import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Award, Bell, ChevronRight, Coffee, Heart, Palette, Settings2, ShieldCheck } from 'lucide-react-native';
import { Screen } from '@/components/Screen'; import { Card, Eyebrow } from '@/components/ui'; import { colors } from '@/lib/theme';
export default function Profile(){return <Screen><View style={s.header}><View style={s.avatar}><Text style={s.avatarText}>A</Text><Text style={s.flower}>🌸</Text></View><Eyebrow>MADE WITH LOVE FOR</Eyebrow><Text style={s.name}>Amina</Text><Text style={s.caption}>Collector of little joys</Text></View>
 <Pressable onPress={()=>router.push('/emergency')}><Card style={s.comfort}><View style={s.comfortIcon}><Heart size={23} color="#fff" fill="#fff"/></View><View style={{flex:1}}><Text style={s.comfortTitle}>Emergency Happiness</Text><Text style={s.comfortText}>For the days that need extra softness</Text></View><ChevronRight size={20} color={colors.rose}/></Card></Pressable>
 <Text style={s.section}>Your favorites</Text><Card style={s.list}><Item icon={<Palette size={19} color="#9A82B2"/>} title="Favorite color" value="Soft lavender"/><Item icon={<Coffee size={19} color="#B5845C"/>} title="Favorite drink" value="Iced coffee" last/><Item icon={<Heart size={19} color={colors.rose}/>} title="Favorite flowers" value="Peonies" last/></Card>
 <Text style={s.section}>Little victories</Text><View style={s.badges}><Badge emoji="☀️" title="Sunshine streak"/><Badge emoji="💧" title="Hydration hero"/><Badge emoji="👑" title="Positive queen"/></View>
 <Text style={s.section}>Settings</Text><Card style={s.list}><Item icon={<Bell size={19} color={colors.gold}/>} title="Daily reminder" value="8:30 PM"/><Item icon={<Settings2 size={19} color={colors.muted}/>} title="Preferences"/><Item icon={<ShieldCheck size={19} color={colors.sage}/>} title="Privacy" last/></Card><Text style={s.footer}>Made for Amina, with entirely too much pink.</Text></Screen>}
function Item({icon,title,value,last}:any){return <View style={[s.item,!last&&s.border]}><View style={s.itemIcon}>{icon}</View><Text style={s.itemTitle}>{title}</Text>{value&&<Text style={s.value}>{value}</Text>}<ChevronRight size={17} color="#C5B7BB"/></View>}; function Badge({emoji,title}:any){return <Card style={s.badge}><Text style={s.badgeEmoji}>{emoji}</Text><Text style={s.badgeTitle}>{title}</Text></Card>}
const s=StyleSheet.create({header:{alignItems:'center',paddingTop:25,paddingBottom:25},avatar:{width:92,height:92,borderRadius:46,backgroundColor:'#F7D5DE',alignItems:'center',justifyContent:'center',marginBottom:16},avatarText:{fontFamily:'BodoniModa_700Bold',fontSize:46,color:colors.rose},flower:{position:'absolute',right:-3,bottom:1,fontSize:23},name:{fontFamily:'BodoniModa_700Bold',fontSize:36,color:colors.ink},caption:{fontFamily:'DMSans_400Regular',fontSize:12,color:colors.muted},comfort:{flexDirection:'row',alignItems:'center',gap:13,backgroundColor:'#FFF0F3',borderColor:'#F6DDE3'},comfortIcon:{width:48,height:48,borderRadius:17,backgroundColor:colors.rose,alignItems:'center',justifyContent:'center'},comfortTitle:{fontFamily:'DMSans_700Bold',fontSize:14,color:colors.ink},comfortText:{fontFamily:'DMSans_400Regular',fontSize:10,color:colors.muted,marginTop:3},section:{fontFamily:'BodoniModa_700Bold',fontSize:22,color:colors.ink,marginTop:24,marginBottom:10},list:{paddingVertical:2},item:{height:58,flexDirection:'row',alignItems:'center'},border:{borderBottomWidth:1,borderBottomColor:'#F3EAE7'},itemIcon:{width:36,alignItems:'flex-start'},itemTitle:{fontFamily:'DMSans_600SemiBold',fontSize:13,color:colors.ink,flex:1},value:{fontFamily:'DMSans_400Regular',fontSize:11,color:colors.muted,marginRight:5},badges:{flexDirection:'row',gap:10},badge:{flex:1,alignItems:'center',paddingHorizontal:7,paddingVertical:14},badgeEmoji:{fontSize:27},badgeTitle:{fontFamily:'DMSans_700Bold',fontSize:9,color:colors.ink,textAlign:'center',marginTop:7},footer:{fontFamily:'DMSans_500Medium',fontSize:10,color:'#B49FA6',textAlign:'center',marginVertical:27}});
